<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMPARANDA [
<!-- List of Swadesh 200 words, across 8 languages. 

Sources:

ALBanian:

  Boretzky  Norbert Boretzky (1975-1976).  Der türkische Einfluß auf
            das Albanische.  Wiesbaden: Harrassowitz.

  Drizari   Nelo Drizari (1957).  Albanian-English and English-Albanian 
            dictionary.  Enlarged ed.  New York: Frederick Ungar.

  Huld      Martin E. Hulde (1983).  Basic Albanian etymologies.
            Columbus, Ohio: Slavica.

  Janson    Bernd Janson (1986).  Etymologische und chronologische
            Untersuchungen zu den Bedingungen des Rhotazismus im Albanischen.
            Frankfurt am Main: Peter Lang.  SUL Green PG9528.J36 1986.

  KandA     Kiçi, Gasper and Hysni Aliko.  English-Albanian
            dictionary.  Italy, 1969.

  Kacori    Thoma Kacori (1979).  A handbook of Albanian.  Sofia
            University.

  Kiçi      Kiçi, Gasper.  Albanian-English dictionary.  Italy, 1976.

  Mann      Stuart E. Mann (1977).  An Albanian historical grammar.  Hamburg: 
            Helmut Buske.  SUL Green PG9519.M35.

ENGlish:

  Barnhart

  OED       Oxford English Dictionary, 2nd. ed.

  Skeat     Walter W. Skeat.  A concise etymological dictionary of the
            English language.  New York, Putnam's, 1980 printing.

  Watkins   Calvert Watkins.  1985. The American Heritage dictionary
            of Indo-European roots.  Boston: Houghton Mifflin.

FREnch:

  BW     Oscar Bloch and W. von Wartburg. 1964. Dictionnaire
            étymologique de la langue française.  4. éd.,
            revue et augm. par W. von Wartburg.  Paris: Presses Universitaires
            de France.

  Dauzat    Albert Dauzat (1938). Dictionnaire étymologique de la
            langue française.  Paris, Larousse.   10th ed.

GERman:

  Kluge     Friedrich Kluge. 1995. Etymologisches Wörterbuch der
            deutschen Sprache.  23., erweit. Aufl., bearb. von Elmar
            Seebold.  Berlin, Walter de Gruyter.  

  Roy.      Roy, Dietrich.  Langenscheidt's standard dictionary of the
            English and German languages.  6th ed.  Berlin, 1970.

HAWaiian:

  Blust.    Robert Blust.  Central and Central-Eastern
            Malayo-Polynesian.  Oceanic Linguistics 32, 2: 241-293.
            1993.

  EP        Elbert, Samuel H. and Mary Kawena Pukui.  Hawaiian
            Grammar.  Honolulu: University of Hawaii Press, 1979.

  Marck     Marck, Jeff (1996). Kin Terms in the Polynesian Protolanguages.
            Oceanic Linguistics, 35, 195-257.

  Pukui and Elbert.  Mary Kawena Pukui and Samuel H. Elbert (1986).  Hawaiian 
            dictionary.  Rev. ed.  Honolulu: Univ. of Hawaii Press.

  Ross.     Malcolm Ross.  Proto-Oceanic terms for meteorological
            phenomena.  Oceanic Linguistics, 34, 2: 261-304.  1995.

LATin:

  Ernout    Ernout, A. and A. Meillet. 1979.  Dictionnaire
            étymologique de la langue latine.  4. éd.,
            3. tirage, augm. d'additions et de corrections nouvelles
            par Jacques André.  Paris: Klincksieck.

  Tucker    T. G. Tucker, Etymological Dictionary of Latin.  Chicago: Ares, 
            1985.

NAVaho:

  Haile     Berard Haile (1926).  A Manual of Navaho Grammar.  Arizona:
            St. Michael's.

  Hoijer    Harry Hoijer.  Navaho phonology.  Albuquerque: Univ. of
            New Mexico Press, 1945.

  Kari      James M. Kari.  Navajo verb prefix phonology.  New York:
            Garland, 1976.

  Pinnow    Heinz-Jürgen Pinnow.  Studie zur Verbstammvariation
            im Navaho.  Berlin: Mann, 1974.

  YandM(1987)  Robert W. Young and William Morgan, Sr.  The Navajo language: 
            A grammar and colloquial dictionary.  Rev. ed.  Albuquerque: 
            Univ. of New Mexico Press.  SUL Green PM2007.Y6 1987

  YandM(1992)  Robert W. Young and William Morgan, Sr.  Analytical lexicon of
            Navajo.  With the assistance of Sally Midgette.  Albuquerque: 
            Univ. of New Mexico Press.  SUL Green PM2007.Y724 1992

TURkish:

  Dankoff   Robert Dankoff.  Armenian loanwords in Turkish.  
            Wiesbaden: Harrassowitz, 1995.

  Iz        Fahir Iz and H. C. Hony (1955).  An English-Turkish dictionary.
            Oxford: Clarendon Press.

  Hony      Hony, H.C. and Fahir Iz.  The Oxford Turkish-English
            dictionary. 3rd ed., A. D. Alderson and Fahir Iz.  Oxford:
            Oxford Univ. Press, 1984.

  Räsänen, Martti.  1969.  Versuch eines etymologischen
            Wörterbuches der Türksprachen.  Helsinki:
            Suomoloais-Ugrilainen Seura.  (Lexica Societatis
            Fenno-Ugricae, 17, 1).

  Stachowski, Stanisław.  Studien über die arabischen Lehnwörter
            im Osmanisch-Türkischen.  Worcław:
            Zakład narodowy imienia ossolin'skich wydawnictwo
            Polskiej akademii nauk, 1986. 

  Steingass, F. 1930. A comprehensive Persian-English dictionary.
            London: Allen. (A source of loans).

  Wehr, Hans. 1979.  A dictionary of modern written Arabic.  Ed. by
            J. Milton Cowan.  4th ed.  Wiesbaden: Harrassowitz. (A
            source of loans).

Indo-European

  Lubotsky, Alexander. 1989.  Against a Proto-Indo-Euopean phoneme *"a".  In
              Vennemann, Theo (Ed.) The new sound of
              Indo-European. Berlin: Mouton de Gruyter.  54-66.

  Pokorny.    Pokorny, Julius.  1959.  Indogermanisches etymologisches
              Wörterbuch,  Bern: Francke.

  Walde.


-->

<!ELEMENT COMPARANDA (CONCEPT+) >
<!ELEMENT CONCEPT    (NOTE?, ALB, ENG, FRE, GER, HAW, LAT, NAV, TUR) >
<!ATTLIST CONCEPT    ID ID #REQUIRED
                     ROLE (act|descr|lim|link|thing) #REQUIRED
                     S200 (yes|no) #REQUIRED>
<!ELEMENT ALB        (WORD, STEM, ROOT, NOTE?)>
<!ATTLIST ALB	     ORTH CDATA #REQUIRED
                     LOAN (yes|no) "no"
                     MOTIV (yes|no) "no"
                     COGN_PROB CDATA ""
                     COGN_POSS CDATA ""
                     BASE CDATA ""
                     DERIVED (yes|no) "no">
<!ELEMENT ENG        (WORD, STEM, ROOT, NOTE?)>
<!ATTLIST ENG	     ORTH CDATA #REQUIRED
                     LOAN (yes|no) "no"
                     MOTIV (yes|no) "no"
                     COGN_PROB CDATA ""
                     COGN_POSS CDATA ""
                     BASE CDATA ""
                     DERIVED (yes|no) "no">
<!ELEMENT FRE        (WORD, STEM, ROOT, NOTE?)>
<!ATTLIST FRE	     ORTH CDATA #REQUIRED
                     LOAN (yes|no) "no"
                     MOTIV (yes|no) "no"
                     COGN_PROB CDATA ""
                     COGN_POSS CDATA ""
                     BASE CDATA ""
                     DERIVED (yes|no) "no">
<!ELEMENT GER        (WORD, STEM, ROOT, NOTE?)>
<!ATTLIST GER	     ORTH CDATA #REQUIRED
                     LOAN (yes|no) "no"
                     MOTIV (yes|no) "no"
                     COGN_PROB CDATA ""
                     COGN_POSS CDATA ""
                     BASE CDATA ""
                     DERIVED (yes|no) "no">
<!ELEMENT HAW        (WORD, STEM, ROOT, NOTE?)>
<!ATTLIST HAW	     ORTH CDATA #REQUIRED
                     LOAN (yes|no) "no"
                     MOTIV (yes|no) "no"
                     COGN_PROB CDATA ""
                     COGN_POSS CDATA ""
                     BASE CDATA ""
                     DERIVED (yes|no) "no">
<!ELEMENT LAT        (WORD, STEM, ROOT, NOTE?)>
<!ATTLIST LAT	     ORTH CDATA #REQUIRED
                     LOAN (yes|no) "no"
                     MOTIV (yes|no) "no"
                     COGN_PROB CDATA ""
                     COGN_POSS CDATA ""
                     BASE CDATA ""
                     DERIVED (yes|no) "no">
<!ELEMENT NAV        (WORD, STEM, ROOT, NOTE?)>
<!ATTLIST NAV	     ORTH CDATA #REQUIRED
                     LOAN (yes|no) "no"
                     MOTIV (yes|no) "no"
                     COGN_PROB CDATA ""
                     COGN_POSS CDATA ""
                     BASE CDATA ""
                     DERIVED (yes|no) "no">
<!ELEMENT TUR        (WORD, STEM, ROOT, NOTE?)>
<!ATTLIST TUR	     ORTH CDATA #REQUIRED
                     LOAN (yes|no) "no"
                     MOTIV (yes|no) "no"
                     COGN_PROB CDATA ""
                     COGN_POSS CDATA ""
                     BASE CDATA ""
                     DERIVED (yes|no) "no">

<!ELEMENT WORD       EMPTY >
<!ATTLIST WORD	     COGNATE  CDATA    ""
                     PHON      CDATA    #REQUIRED>
<!ELEMENT STEM       EMPTY >
<!ATTLIST STEM	     COGNATE  CDATA    ""
                     PHON CDATA #REQUIRED>
<!ELEMENT ROOT       EMPTY >
<!ATTLIST ROOT	     COGNATE  CDATA    ""
                     PHON CDATA #REQUIRED>
<!ELEMENT NOTE       (#PCDATA) >

<!ENTITY Ras "Räsänen">

]>
<COMPARANDA>

<CONCEPT ID="all" ROLE="lim" S200="no">
  <NOTE>plural, e.g.: All Cretans are liars</NOTE>
  <ALB ORTH="gjithë" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="ɟ i θ ə" COGNATE=""/>
    <STEM PHON="ɟ i θ" COGNATE=""/>
    <ROOT PHON="ɟ i" COGNATE=""/>
    <NOTE>Meyer suggested a loan
      from Kurdish, but generally considered PIE "sem-k̑o-", root
      "sem" `one'.  Huld 69. Mann 109.  Walde 489*.  Pokorny 903.
      <!-- Ringe 1993 has /dʹiθə/.-->
    </NOTE> 
  </ALB>
  <ENG ORTH="all" COGN_PROB="ger" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="ɔ l" COGNATE=""/>
    <STEM PHON="ɔ l" COGNATE=""/>
    <ROOT PHON="ɔ l" COGNATE=""/>
    <NOTE>PG "alla-", PIE root "al-".
      Walde 90.  Pokorny 25.  Kluge "all".  Watkins "al-5". 
      <!-- Ringe 1992: /ol/. Presumed PIE root "al-" possibly
      connected with LAT "alius" `other'.   -->
    </NOTE>
    </ENG>
  <FRE ORTH="tous" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="t u" COGNATE=""/>
    <STEM PHON="t u t" COGNATE=""/>
    <ROOT PHON="t u" COGNATE=""/>
    <NOTE>Pop. Lat. "tottus" for Classical "tōtus", replacing the
      unrelated "omnis".  PIE "tēu-" `swell'. Pokorny 1080. BW.
      <!-- Ringe 1993: /tus/, fem. /tut/. "tēu-" gives  also
        "tumeō" `swell'. Watkins factors out
        "teutā-" `tribe' as a separate root possibly underlying
        "totus".    -->
    </NOTE>
  </FRE>
  <GER ORTH="alle" COGN_PROB="eng" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a l ə" COGNATE=""/>
    <STEM PHON="a l" COGNATE=""/>
    <ROOT PHON="a l" COGNATE=""/>
    <NOTE>PG "alla-", PIE root "al-".  Walde 90, Pokorny 25, Kluge
      "all", Watkins "al-5".  
      <!-- Ringe 1992: /alə/. Presumed PIE root "al-" might
      connect with LAT "alius" `other'. --> 
    </NOTE>
  </GER>
  <HAW ORTH="apau" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a p a u" COGNATE=""/>
    <STEM PHON="a p a u" COGNATE=""/>
    <ROOT PHON="p a u" COGNATE=""/>
    <NOTE>Since "a-" is a common prefix, perhaps etymologically
      connected with "pau" (PNP "pau"), which can share the meaning
      `completely'.  PE.
      <!-- Ringe 1992: /apau/. --> 
    </NOTE>
  </HAW>
  <LAT ORTH="omnes" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="o m n eː s" COGNATE=""/>
    <STEM PHON="o m n i" COGNATE=""/>
    <ROOT PHON="o m" COGNATE=""/>
    <NOTE>Best guess is *"opnis",
      PIE root "op" `work'.  EM. Sihler 43. Walde
      123. Pokorny 780.  Watkins "op-1".
      <!-- Ringe 1992: /omnēs/.  --> 
    </NOTE>
  </LAT>
  <NAV ORTH="t'áá 'áƚtso" BASE="big" DERIVED="yes" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS=""> 
    <WORD PHON="tˀ áː ʔ áy ɬ ts o" COGNATE=""/>
    <STEM PHON="ʔ áy ɬ ts o" COGNATE=""/>
    <ROOT COGNATE="big" PHON="ts o h"/>
    <NOTE>The "t'áá" is a
      particularizing particle used in dozens of expressions; the
      distinctive word is "'aƚtso", root "tsoh" `big', q.v.  YM
      1992, p. 613 (TSOH), 932, 954.  Haile 38.
      <!-- Ringe 1992: /t'áá
        ʔaƚco/.    --> 
    </NOTE>
  </NAV>
  <TUR ORTH="bütün" DERIVED="yes" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="">
    <WORD PHON="b y t y n" COGNATE=""/>
    <STEM PHON="b y t y n" COGNATE=""/>
    <ROOT PHON="b y t" COGNATE=""/>
    <NOTE>Räsänen derives from
      "büt" `finish, be complete'. Räsänen 93b. 
      <!-- Ringe 1992: /bütün/.   --> 
    </NOTE>
  </TUR>
</CONCEPT>

<CONCEPT ID="and" ROLE="link" S200="yes">
  <ALB ORTH="e" LOAN="yes" COGN_PROB="fre,lat" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="e" COGNATE=""/>
    <STEM PHON="e" COGNATE=""/>
    <ROOT PHON="e" COGNATE=""/>
    <NOTE>Generally considered a loan from LAT, but possibly native, perhaps
      cognate.  Mann 209, Huld 60. Not in Pokorny. 
      <!-- Meyer, Tagliavini, Çabej, Rosetti, Hamp treat as
      loan.  Other words for `and' are "dhe" and "edhe" (compound). -->
    </NOTE>
  </ALB>
  <ENG ORTH="and" COGN_PROB="ger" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a n d" COGNATE=""/>
    <STEM PHON="a n d" COGNATE=""/>
    <ROOT COGNATE="in" PHON="a n"/>
    <NOTE>Cognate with GER "und". The two main
      theories are that these words are related to Lat. "ante", PIE
      "H₂anti" `facing'; and that they connect with "en" `in'. OED.
      Skeat. Walde 67. Pokorny 50. Kluge "und".  Watkins "en".
      <!-- Ringe 1992: /ænd/.  ("in")  -->
    </NOTE>
  </ENG>
  <FRE ORTH="et" COGN_PROB="alb,lat" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="e" COGNATE=""/>
    <STEM PHON="e" COGNATE=""/>
    <ROOT PHON="e" COGNATE=""/>
    <NOTE>From LAT "et".  BW.
    </NOTE>
  </FRE>
  <GER ORTH="und" COGN_PROB="eng" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="u n t" COGNATE=""/>
    <STEM PHON="u n t" COGNATE=""/>
    <ROOT COGNATE="in" PHON="u n"/>
    <NOTE>PIE "H₂anti" `facing' or "en" `in'.  
      Skeat. Walde 67. Pokorny 50. Kluge "und".  Watkins "en".
    </NOTE>
  </GER>
  <HAW ORTH="ā" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="aː" COGNATE=""/>
    <STEM PHON="aː" COGNATE=""/>
    <ROOT PHON="aː" COGNATE=""/>
    <NOTE>PCP "a".  PE.
    </NOTE>
  </HAW>
  <LAT ORTH="et" COGN_PROB="alb,fre" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="e t" COGNATE=""/>
    <STEM PHON="e t" COGNATE=""/>
    <ROOT PHON="e t" COGNATE=""/>
    <NOTE>PIE "eti" `beyond'.  EM.  Sihler 441.
      Pokorny 344.  Watkins "eti".
      <!-- Ringe 1992: /et/.    -->
    </NOTE>
  </LAT>
  <NAV ORTH="dóó" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="d óː" COGNATE=""/>
    <STEM PHON="d óː" COGNATE=""/>
    <ROOT PHON="d óː" COGNATE=""/>
    <NOTE>YM 1992, p. 938, 943.
    </NOTE>
  </NAV>
  <TUR ORTH="ve" LOAN="yes" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="v e" COGNATE=""/>
    <STEM PHON="v e" COGNATE=""/>
    <ROOT PHON="v e" COGNATE=""/>
    <NOTE>Loan from Arabic "wa".  Not in Räsänen.  Wehr 1224.
    </NOTE>
  </TUR>
</CONCEPT>

<CONCEPT ID="animal" ROLE="thing" S200="yes">
  <ALB ORTH="kafshë" LOAN="yes" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="k a f ʃ ə" COGNATE=""/>
    <STEM PHON="k a f ʃ" COGNATE=""/>
    <ROOT PHON="k a f ʃ" COGNATE=""/>
    <NOTE>Also means `thing', and is a loan from Lat. "causa", which
      has no known cognates.  Mann 2. Huld 79 (citing also Meyer,
      Haarmann).  EM "causa".  Not in Pokorny.
    </NOTE>
  </ALB>
  <ENG ORTH="animal" LOAN="yes" COGN_PROB="fre,lat" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a n ə m ə l" COGNATE=""/>
    <STEM PHON="a n ə m ə l" COGNATE=""/>
    <ROOT PHON="a n ə" COGNATE=""/>
    <NOTE>Loan from LAT.  Skeat. 
      <!-- Ringe 1992: /ænəməl/.   -->
    </NOTE>
  </ENG>
  <FRE ORTH="animal" LOAN="yes" COGN_PROB="eng,lat" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a n i m a l" COGNATE=""/>
    <STEM PHON="a n i m a l" COGNATE=""/>
    <ROOT PHON="a n i" COGNATE=""/>
    <NOTE>Loan from LAT (native development of "animalia" was
      "aumaille").  BW. 
    </NOTE>
  </FRE>
  <GER ORTH="Tier" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="t iː r" COGNATE=""/>
    <STEM PHON="t iː r" COGNATE=""/>
    <ROOT PHON="t iː" COGNATE=""/>
    <NOTE>PG "deuza-", PIE "dhewes", PIE "dheu-" `fly about'.  Pokorny
      261. Kluge.  
      <!-- = Eng. "deer".  dheu- > Lat. "fumus" `smoke',
      (Eng. "dust") ENG "dull" -->
    </NOTE>
  </GER>
  <HAW ORTH="holoholona" DERIVED="yes" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="">
    <WORD PHON="h o l o h o l o n a" COGNATE=""/>
    <STEM PHON="h o l o h o l o n a" COGNATE=""/>
    <ROOT PHON="h o l o" COGNATE=""/>
    <NOTE>Root is "holo" `run', from PPN "solo".  PE.
    </NOTE>
  </HAW>
  <LAT ORTH="animal" COGN_PROB="eng,fre" DERIVED="yes" LOAN="no" MOTIV="no" COGN_POSS="" BASE="">
    <WORD PHON="a n i m a l" COGNATE=""/>
    <STEM PHON="a n i m aː l" COGNATE=""/>
    <ROOT PHON="a n i" COGNATE=""/>
    <NOTE>Nominalization of adj. "animālis", from "anima", PIE 
      "H₂anH₁-" `breathe'.  Sihler 46.  Walde 56.  Pokorny
      38.  Watkins "anə-".
      <!-- Pokorny derives Alb. "ënj" `swell' from the
      same source.  --> 
    </NOTE>
  </LAT>
  <NAV ORTH="naaldeehii" DERIVED="yes" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="">
    <WORD PHON="n aː l d eː h iː" COGNATE=""/>
    <STEM PHON="n aː l d eː h iː" COGNATE=""/>
    <ROOT PHON="d eː ʔ" COGNATE=""/>
    <NOTE>The root means approximately "multiple objects moving
      through space". PA "de̓G", PPA "de'G".  YM 1992,
      p. 128, "DEE'". 
    </NOTE>
  </NAV>
  <TUR ORTH="hayvan" LOAN="yes" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="h a j v a n" COGNATE=""/>
    <STEM PHON="h a j v a n" COGNATE=""/>
    <ROOT PHON="h j" COGNATE=""/>
    <NOTE>Via Persian from Arabic "ḥaywān", root `alive'.
      Räsänen 153a.  Wehr 257.
    </NOTE>
  </TUR>
</CONCEPT>

<CONCEPT ID="ashes" ROLE="thing" S200="no">
  <ALB ORTH="hi" COGN_POSS="fre,lat" LOAN="no" MOTIV="no" COGN_PROB="" BASE="" DERIVED="no">
    <WORD PHON="h i" COGNATE=""/>
    <STEM PHON="h i r" COGNATE=""/>
    <ROOT PHON="h i r" COGNATE=""/>
    <NOTE>PAlb "hin-", possibly cognate to the LAT "cinis" as
      "sk̑ino-", though there are problems. Huld 74.  Walde 392.  
      <!-- Ringe 1993: /hi/.     -->
    </NOTE>
  </ALB>
  <ENG ORTH="ashes" COGN_PROB="ger" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a ʃ ə z" COGNATE=""/>
    <STEM PHON="a ʃ" COGNATE=""/>
    <ROOT PHON="a ʃ" COGNATE=""/>
    <NOTE>PG "H₂ask-" or "H₂azg-", velar extension of PIE
      "H₂as-" `hearth', from `burn'.  Skeat.  OED.  Pokorny
      69. Kluge "Asche". Watkins "as-". 
      <!-- Ringe 1992: /æšəz/.  That would tie in
        with Lat. "ardeo" `burn', 
        "areo" `be dry'.     -->
    </NOTE>
  </ENG>
  <FRE ORTH="cendre" COGN_PROB="lat" COGN_POSS="alb" LOAN="no" MOTIV="no" BASE="" DERIVED="no">
    <WORD PHON="s ɑ̃ d r" COGNATE=""/>
    <STEM PHON="s ɑ̃ d r" COGNATE=""/>
    <ROOT PHON="s ɑ̃" COGNATE=""/>
    <NOTE>LAT "cinerem".  BW.
      <!-- Ringe 1993: /sądrə/.    -->
    </NOTE>
  </FRE>
  <GER ORTH="Asche" COGN_PROB="eng" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a ʃ ə" COGNATE=""/>
    <STEM PHON="a ʃ ə" COGNATE=""/>
    <ROOT PHON="a ʃ" COGNATE=""/>
    <NOTE>PG "H₂ask-" or "H₂azg-", as ENG.
      Skeat.  OED.  Pokorny 69. Kluge "Asche".  Watkins "as-". 
      <!-- Ringe 1992: /ašə/.  -->
    </NOTE>
  </GER>
  <HAW ORTH="lehu" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="l e h u" COGNATE=""/>
    <STEM PHON="l e h u" COGNATE=""/>
    <ROOT PHON="l e h u" COGNATE=""/>
    <NOTE>PPN "refu". Cf. POc. "qapu".  PE.  Blust.
      <!-- Ringe 1992: /lehu/.    -->
    </NOTE>
  </HAW>
  <LAT ORTH="cinis" COGN_PROB="fre" COGN_POSS="alb" LOAN="no" MOTIV="no" BASE="" DERIVED="no">
    <WORD PHON="k i n i s" COGNATE=""/>
    <STEM PHON="k i n e r" COGNATE=""/>
    <ROOT PHON="k i n" COGNATE=""/>
    <NOTE>Best guess for
      PIE root is "ken" `scratch', possibly "sk̑in" if ALB ties
      in.  Sihler 37. Walde 392, Pokorny 560.  EM.  Watkins
      "keni-".
      <!-- Ringe 1992: /kinis, kiner-/. (FRE "cendre").     -->
    </NOTE>
  </LAT>
  <NAV ORTH="ƚeeshch'ih" BASE="earth" DERIVED="yes" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="">
    <WORD PHON="ɬ eː ʃ tʃˀ i h" COGNATE=""/>
    <STEM PHON="ɬ eː ʃ tʃˀ i h" COGNATE=""/>
    <ROOT COGNATE="dust,earth" PHON="ɬ eː ʒ"/>
    <NOTE>"Łeezh" by itself means `dirt, soil, ashes' plus
      "ch'ih"  `blows'.  YM 1992, p. 104 (CH'I), 393.
      <!-- Ringe 1992: /ƚeešč'ih/.
      perf. root "ch'i"  -->
    </NOTE>
  </NAV>
  <TUR ORTH="kül" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="k y l" COGNATE=""/>
    <STEM PHON="k y l" COGNATE=""/>
    <ROOT PHON="k y l" COGNATE=""/>
    <NOTE>Räsänen 307b.
      <!-- Ringe 1992: /kül/.   -->
    </NOTE>
  </TUR>
</CONCEPT>

<CONCEPT ID="at" ROLE="link" S200="yes">
  <ALB ORTH="në" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD COGNATE="if,in" PHON="n ə"/>
    <STEM COGNATE="in" PHON="n ə"/>
    <ROOT COGNATE="in" PHON="n ə"/>
    <NOTE>`In, on, at'; source perhaps PIE "endo". 
      Mann 207.  Huld 97 (citing Meyer, Tagliavini, Jokl, Rosetti).
      <!-- Seems to be a general locative.
        -->
    </NOTE>
  </ALB>
  <ENG ORTH="at" COGN_PROB="fre,lat" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a t" COGNATE=""/>
    <STEM PHON="a t" COGNATE=""/>
    <ROOT PHON="a t" COGNATE=""/>
    <NOTE>PIE "H₂ad" `to, at'. Skeat.  Walde 45.  Pokorny 3.  OED.
      Sihler 441.  Watkins "ad-".
      <!--  Ringe 1992: /æt/.    -->
    </NOTE>
  </ENG>
  <FRE ORTH="à" COGN_PROB="eng,lat" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a" COGNATE=""/>
    <STEM PHON="a" COGNATE=""/>
    <ROOT PHON="a" COGNATE=""/>
    <NOTE>From LAT.    BW.
      <!--  A productive prefix: cf. `lie',
        `sit', and `tie'.   -->
    </NOTE>
  </FRE>
  <GER ORTH="an" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a n" COGNATE=""/>
    <STEM PHON="a n" COGNATE=""/>
    <ROOT COGNATE="near" PHON="a n"/>
    <NOTE>PG "ana", extension of "an".  Pokorny suggests a
      connection to "nahe" `near'.  Walde 58.  Pokorny 39.
      Kluge. Watkins "an-1".
      <!-- Eng. "on"  -->
    </NOTE>
  </GER>
  <HAW ORTH="ma" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="m a" COGNATE=""/>
    <STEM PHON="m a" COGNATE=""/>
    <ROOT PHON="m a" COGNATE=""/>
    <NOTE>PCP "ma".  PE.
    </NOTE>
  </HAW>
  <LAT ORTH="ad" COGN_PROB="eng,fre" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a d" COGNATE=""/>
    <STEM PHON="a d" COGNATE=""/>
    <ROOT PHON="a d" COGNATE=""/>
    <NOTE>PIE "H₂ad". Pokorny 3.  EM.
      <!-- Ringe 1992: /ad/. (FRE "à") (ENG "at").  -->
    </NOTE>
  </LAT>
  <NAV ORTH="-di" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="d i" COGNATE=""/>
    <STEM PHON="d i" COGNATE=""/>
    <ROOT PHON="d i" COGNATE=""/>
    <NOTE>YM 1992, p. 939.
      <!-- Enclitic used for expressing general or remote location.    -->
    </NOTE>
  </NAV>
  <TUR ORTH="-de" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="d e" COGNATE=""/>
    <STEM PHON="d e" COGNATE=""/>
    <ROOT PHON="d e" COGNATE=""/>
    <!-- Redhouse Sözlüğü. -->
  </TUR>
</CONCEPT>

<CONCEPT ID="back" ROLE="thing" S200="yes">
  <ALB ORTH="shpinë" LOAN="yes" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="ʃ p i n ə" COGNATE=""/>
    <STEM PHON="ʃ p i n" COGNATE=""/>
    <ROOT PHON="ʃ p i" COGNATE=""/>
    <NOTE>Loan from Lat. "spīna" `thorn, backbone', from PIE
      "spei-nā-", root "spei".  Not in Mann, Huld. 
      Çabej 131.  Janson 113.  EM "spīna".  Pokorny
      981.  Watkins "spei-".
      <!-- connected to Eng. "spit"
        `stick', "spike", "spire"  -->
    </NOTE>
  </ALB>
  <ENG ORTH="back" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="b a k" COGNATE=""/>
    <STEM PHON="b a k" COGNATE=""/>
    <ROOT PHON="b a k" COGNATE=""/>
    <NOTE>PG "bakom".  Skeat. OED.  Not in Pokorny. 
      <!--  Ringe 1992: /bæk/.  -->
    </NOTE>
  </ENG>
  <FRE ORTH="dos" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="d o" COGNATE=""/>
    <STEM PHON="d o" COGNATE=""/>
    <ROOT PHON="d o" COGNATE=""/>
    <NOTE>Pop. Lat. "dossum", Class. "dorsum".  I assume
      "-so-" is a suffix.  BW.  Not in Pokorny. EM 184.  Watkins
      [dorsum]. 
    </NOTE>
  </FRE>
  <GER ORTH="Rücken" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="r y k ə n" COGNATE=""/>
    <STEM PHON="r y k ə n" COGNATE=""/>
    <ROOT PHON="r" COGNATE=""/>
    <NOTE>From PG "hrugjaz", PIE "kreuk-", extension of "(s)ker",
      `turn'.   Kluge.  Pokorny 938.  Watkins "sker".
      <!-- PG "hrugjaz" (Eng. "ridge")  Possibly a connection to the "ker" of
      Lat. "cervix" `neck' (`horn, head') and/or of Lat. "crassus"
      `thick', whence Fre. "graisse", Eng. "grease".  --> 
    </NOTE>
  </GER>
  <HAW ORTH="kua" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="k u a" COGNATE=""/>
    <STEM PHON="k u a" COGNATE=""/>
    <ROOT PHON="k u a" COGNATE=""/>
    <NOTE>PPN "tu`a". POc word is "muri".  PE.
    </NOTE>
  </HAW>
  <LAT ORTH="tergum" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="t e r g u m" COGNATE=""/>
    <STEM PHON="t e r g o" COGNATE=""/>
    <ROOT PHON="t e r" COGNATE=""/>
    <NOTE>There is no certain etymology beyond Latin, but one guess is
      a PIE "(s)terg" `stretch', root "(s)ter" `stiff'.  Tucker further 
      suggests a connection with "terra", but that's very dubious.
      Walde 629*. Pokorny 1023.
      <!-- Ringe 1992: /tergum/.  (whence ENG "stork", "stark") -->
    </NOTE>
  </LAT>
  <NAV ORTH="'anághah" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="ʔ a n áy ɣ a h" COGNATE=""/>
    <STEM PHON="n áy ɣ a h" COGNATE=""/>
    <ROOT PHON="n áy" COGNATE=""/>
    <NOTE>Dependent stem noun. Probably "ná" `back' + "ghah".
      YM 1992, p. 988. 
    </NOTE>
  </NAV>
  <TUR ORTH="arka" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="a r k a" COGNATE=""/>
    <STEM PHON="a r k a" COGNATE=""/>
    <ROOT PHON="a r k a" COGNATE=""/>
    <NOTE>Räsänen 26a.  
    </NOTE>
  </TUR>
</CONCEPT>

<CONCEPT ID="bad" ROLE="descr" S200="yes">
  <ALB ORTH="keq" MOTIV="yes" LOAN="yes" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="k e c" COGNATE=""/>
    <STEM PHON="k e c" COGNATE=""/>
    <ROOT PHON="k e c" COGNATE=""/>
    <NOTE>Generally believed to be a loan from Greek "kakos", although
      this isn't clear; it could be native.  Either way, it sounds
      like a common nursery word, /kaka/.  Mann 112.  Huld 79.  Walde
      336. 
    </NOTE>
  </ALB>
  <ENG ORTH="bad" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="b a d" COGNATE=""/>
    <STEM PHON="b a d" COGNATE=""/>
    <ROOT PHON="b a d" COGNATE=""/>
    <NOTE>OED, Skeat. 
      <!-- Ringe 1992: /bæd/.  No known etymology.    -->
    </NOTE>
  </ENG>
  <FRE ORTH="mauvais" COGN_PROB="lat" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="m ɔ v ɛ z" COGNATE=""/>
    <STEM PHON="m ɔ v ɛ z" COGNATE=""/>
    <ROOT PHON="m ɔ" COGNATE=""/>
    <NOTE>Pop. Lat. "malifātius" `ill-fated'. The first element is
      descendant of LAT "malus". BW.
      <!-- the second element
      is connected to the second element in "enfant" `child': "fa"
      `speak' (PIE "bhā").     -->
    </NOTE>
  </FRE>
  <GER ORTH="schlecht" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="ʃ l e x t" COGNATE=""/>
    <STEM PHON="ʃ l e x t" COGNATE=""/>
    <ROOT COGNATE="liver" PHON="ʃ l e"/>
    <NOTE>PG "slihta-" `level, smooth' (Eng. "slight"), base "slik-".
      Generally referred to "(s)lei-" `slip,
      slimy'.  "Leip" `fat', basis of "Leber", "liver", may be a "-p-"
      extension.  Walde 391*. Pokorny 504. Kluge.
      <!-- a "-to-"
      adjective, base > Eng. "slick"  -->
    </NOTE>
  </GER>
  <HAW ORTH="`ino" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="ʔ i n o" COGNATE=""/>
    <STEM PHON="ʔ i n o" COGNATE=""/>
    <ROOT PHON="ʔ i n o" COGNATE=""/>
    <NOTE>PNP "kino". PE.
    </NOTE>
  </HAW>
  <LAT ORTH="malus" COGN_PROB="fre" LOAN="no" MOTIV="no" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="m a l u s" COGNATE=""/>
    <STEM PHON="m a l o" COGNATE=""/>
    <ROOT PHON="m a l" COGNATE=""/>
    <NOTE>FRE "mau(vais)".  PIE root "mel" `bad', conceivably
      "(s)mēlo-" `small animal'.  Walde 291*, 296*.  Pokorny 724. 
      EM.  Watkins "mel-5", "mēlo-".
      <!-- Ringe 1992: /malus/.  -->
    </NOTE>
  </LAT>
  <NAV ORTH="doo yá'áshǫ́ǫ da" DERIVED="yes" LOAN="no" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE=""> 
    <WORD COGNATE="not" PHON="d oː j áy ʔ áy ʃ         ṍ õ d a"/> 
    <STEM PHON="j áy ʔ áy ʃ ṍ õ" COGNATE=""/>
    <ROOT PHON="ʒ oː" COGNATE=""/>
    <NOTE>`It is not good', neuter imperf.; root is `good'.  PA
      "zhu-nʸ", PPA "shu".  Haile.  YM 1992, p. 795--6,
      "ZHǪǪD". 
    </NOTE>
  </NAV>
  <TUR ORTH="kötü" LOAN="yes" MOTIV="no" COGN_PROB="" COGN_POSS="" BASE="" DERIVED="no">
    <WORD PHON="k ø t y" COGNATE=""/>
    <STEM PHON="k ø t y" COGNATE=""/>
    <ROOT PHON="k ø t y" COGNATE=""/>
    <NOTE>Not in Räsänen.  Dankoff, p. 163: may be a loan from Arm. /godi/.
    </NOTE>
  </TUR>
</CONCEPT>
